package app.junhyounglee.archroid.runtime.core

import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.fragment.app.DialogFragment
import androidx.fragment.app.FragmentActivity
import androidx.fragment.app.FragmentManager
import androidx.lifecycle.LifecycleObserver
import app.junhyounglee.archroid.runtime.core.presenter.MvpPresenter
import app.junhyounglee.archroid.runtime.core.view.MvpView

/**
 * Abstract base class that is used to generate fragment extended view using MvpDialogFragmentView
 * annotation. archroid-compiler will generate following codes for users.
 *
 * prerequisite:
 *  [MvpView interface]
 *  interface SampleView : MvpView
 *
 *  [MvpPresenter class]
 *  class SamplePresenter(view: SampleView) : MvpPresenter<SampleView>(view)
 *
 * auto-generated code by archroid-compiler will be:
 *  abstract class MvpSampleDialogFragmentView
 *      : MvpDialogFragmentLifecycleController<MvpView, MvpPresenter<MvpView>>()
 *      , SampleView {
 *
 *      private val impl = RootViewImpl()
 *
 *      override var rootView: ViewGroup
 *        get() = if (impl.isViewAlive) {
 *          impl.container!!
 *        } else {
 *          throw NullPointerException("Root content view is null!")
 *        }
 *        set(value) {
 *          impl.container = value
 *        }
 *
 *       override val isRootViewAlive: Boolean
 *         get() = impl.isViewAlive
 *
 *       override val layoutResId: Int
 *         get() = R.layout.dialog_fragment_sample
 *
 *       override fun onCreateMvpView(): SampleView = this
 *
 *       override fun onCreateMvpPresenter(): SamplePresenter = SamplePresenter(this)
 *
 *  Finally, actual MVP dialog fragment view  will be like this:
 *
 *   @MvpDialogFragmentView(SampleView::class, layoutResId = R.layout.activity_sample)
 *   @BindMvpPresenter(SamplePresenter::class)
 *   class SampleDialogFragmentView : MvpSampleDialogFragmentView() {
 *     ...
 *   }
 *
 *   MvpDialogFragmentView annotation only support creation of the dialog fragment through
 *   onCreateView callback rather than onCreateDialog. Most of the dialogs generated by onCreateDialog
 *   has simple interface, and those dialog fragment is regarded as a part of view which is not a
 *   subject of separate MvpView object.
 */
abstract class MvpDialogFragmentLifecycleController<VIEW : MvpView, PRESENTER : MvpPresenter<VIEW>>
    : DialogFragment()
    , MvpLifecycleController<VIEW, PRESENTER> {

    private lateinit var _presenter: PRESENTER

    override val view: VIEW by lazy {
        onCreateMvpView().also {
            _presenter = onCreateMvpPresenter(it)
        }
    }

    override val presenter: PRESENTER
        get() = if (this::_presenter.isInitialized) {
            _presenter
        } else {
            throw IllegalStateException("Presenter is not initialized yet!")
        }

    override val hostActivity: FragmentActivity?
        get() = activity

    override val hostFragmentManager: FragmentManager?
        get() = activity?.supportFragmentManager


    abstract fun onCreateMvpView(): VIEW

    abstract fun onCreateMvpPresenter(view: VIEW): PRESENTER

    override fun onCreateView(
        inflater: LayoutInflater,
        container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View? {
        return if (view.layoutResId != 0) {
            inflater.inflate(view.layoutResId, container, false).also {
                onRootViewCreated(it as ViewGroup)
            }
        } else {
            super.onCreateView(inflater, container, savedInstanceState)
        }
    }

    override fun onDestroy() {
        super.onDestroy()

        if (presenter is LifecycleObserver) {
            lifecycle.removeObserver(presenter as LifecycleObserver)
        }
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        if (presenter is LifecycleObserver) {
            lifecycle.addObserver(presenter as LifecycleObserver)
        }
    }

    private fun onRootViewCreated(container: ViewGroup) {
        view.container = container
    }
}
